language: node_js

node_js:
  - 'node'
  - '12'

branches:
  only:
  - develop

install:
  - npm install

cache:
  directories:
    - node_modules
       
script: 
  - npm run build
  - git add .
  - git commit -m "push master"
  - git push origin master